# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32e76c0a6cf4d9e2375b6fbd70ce365e38f6e35dd6c10758297741bc74fb144cd4621e4fe3708c7548c0027d1daba4fb841207b32d7c710376c53bdc516ba8ff

test:
  secret_key_base: 85ad05971e0036df56b476c4d683192511a6feffea05caafd1d6d8052634ff1267d1abb36d7268e26881febb9bc8751c78e52488f18baea8cb6ada0ca4fdcb34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
